main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

micro_blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('posts/', include('posts.urls', namespace='posts')),
]

posts/urls.py
from posts import views
from django.urls import path

app_name = 'posts'

urlpatterns = [
    path('', views.posts, name='posts'),
    path('post/<int:post_id>/', views.post_detail, name='post_detail'),
    path('like/<int:post_id>/', views.post_grade_like, name='grade_like'),
    path('dislike/<int:post_id>/', views.post_grade_dislike, name='grade_dislike'),
    path('post-create/', views.post_create, name='post_create'),
    path('post-update/<int:post_id>/', views.post_update, name='post_update'),
    path('post-delete/<int:post_id>/', views.post_delete, name='post_delete'),
    path('post/<int:post_id>/comment-delete/<int:comment_id>/', views.comment_delete, name='comment_delete'),
]

main/models.py
from django.db import models


class SiteSettings(models.Model):
    site_name = models.CharField(max_length=50, default='Micro Blog')
    site_description = models.TextField(default='')

    def __str__(self):
        return self.site_name

posts/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    name = models.CharField(max_length=200, verbose_name='Название')
    description = models.TextField(default='', verbose_name='Описание')
    text = models.TextField(default='', verbose_name='Текст')
    status = models.BooleanField(default=False, verbose_name='Статус публикации')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')

    class Meta:
        ordering = ('-created_at', )

    def __str__(self):
        return self.text[:300]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comment')
    text = models.TextField(default='', verbose_name='Комментарий')
    author = models.CharField(max_length=50, verbose_name='Автор', default='Гость')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        ordering = ('-created_at', )

    def __str__(self):
        return self.text


class Grade(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='grade')
    grade_status = models.BooleanField(null=True)
    ip = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')


class Watcher(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='watcher')
    ip = models.CharField(max_length=50)
    counter = models.PositiveIntegerField(default=0)

posts/forms.py
from django import forms
from posts.models import Post


class CreatePostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['author', 'name', 'description', 'text', 'status']
        labels = {
            'author': 'Автор',
            'name': 'Название',
            'description': 'Описание',
            'text': 'Содержание',
            'status': 'Статус (Открытый/Закрытый)',
        }

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from main.models import SiteSettings
from posts.models import Post


def index(request):
    settings = SiteSettings.objects.last()
    post_list = Post.objects.filter(status=True)[:10]
    context = {
        'settings': settings,
        'post_list': post_list,
    }
    return render(request, 'main/index.html', context)

posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from posts.models import Post, Comment, Grade, Watcher
from posts.forms import CreatePostForm
from smart.get_ip_master import IpMaster


def posts(request):
    post_list = Post.objects.filter(status=True)

    paginator = Paginator(post_list, 5)
    page = request.GET.get('page')
    objects = paginator.get_page(page)
    context = {
        'objects': objects,
    }
    return render(request, 'posts/post_list.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    ip = IpMaster.get_ip(request=request)
    watcher = Watcher.objects.filter(ip=ip, post_id=post.id)
    if watcher.exists():
        update_watcher = Watcher.objects.get(ip=ip, post_id=post.id)
        update_watcher.counter += 1
        update_watcher.save()
    else:
        watch = Watcher.objects.create(ip=ip, post_id=post.id, counter=1)
        watch.save()
    comment_list = Comment.objects.filter(post_id=post.id)
    author = request.POST.get('new_author', None)
    new_comment = request.POST.get('new_comment', None)
    if 'btn' in request.POST:
        comment = Comment.objects.create(
            author=author or 'Гость',
            text=new_comment,
            post_id=post.id,
        )
        comment.save()
        return redirect(reverse('posts:post_detail', args=(post.id,)))
    paginator = Paginator(comment_list, 5)
    comment = request.GET.get('page')
    objects = paginator.get_page(comment)
    context = {
        'post': post,
        'objects': objects,
    }
    return render(request, 'posts/post_detail.html', context)


def post_grade_like(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    ip = IpMaster.get_ip(request=request)
    grade = Grade.objects.filter(post_id=post.id, ip=ip, grade_status=True).exists()
    if grade:
        return redirect(reverse('posts:post_detail', args=(post.id,)))
    else:
        create_grade = Grade.objects.create(
            post_id=post.id,
            grade_status=True,
            ip=ip,
        )
        create_grade.save()
        return redirect(reverse('posts:post_detail', args=(post.id,)))


def post_grade_dislike(request, post_id):
    post_id = get_object_or_404(Post, id=post_id)
    ip = IpMaster.get_ip(request=request)
    grade = Grade.objects.filter(post_id=post_id.id, ip=ip, grade_status=False).exists()
    if grade:
        return redirect(reverse('posts:post_detail', args=(post_id.id,)))
    else:
        create_grade = Grade.objects.create(
            post_id=post_id.id,
            grade_status=False,
            ip=ip,
        )
        create_grade.save()
        return redirect(reverse('posts:post_detail', args=(post_id.id,)))


def post_create(request):
    form = CreatePostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('posts:posts'))
    context = {
        'form': form,
    }
    return render(request, 'posts/post_create.html', context)


def post_update(request, post_id):
    post = Post.objects.get(id=post_id)
    form = CreatePostForm(request.POST, instance=post.id)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('posts:posts'))
    context = {
        'post': post,
        'form': form,
    }
    return render(request, 'posts/post_update.html', context)


def post_delete(request, post_id):
    post = Post.objects.get(id=post_id)
    post.delete()
    return redirect('posts:posts')


def comment_delete(request, post_id, comment_id):
    post = Post.objects.get(id=post_id)
    comment = Comment.objects.get(id=comment_id)
    comment.delete()
    return redirect(reverse('posts:post_detail', args=(post.id,)))

main/templates/main/index.html
{% extends 'base.html' %}
{% load post_tags %}

{% block content %}
    <h1 style="font-size: 36px" class="text-center text-primary">{{ settings.site_description }}</h1>
    <hr>
    {% for post in post_list %}
        <ul class="list-group" style="box-shadow: 0 0 10px #CFE2FF">
  <li class="list-group-item active">Дата публикации: {{ post.updated_at }}</li>
  <li class="list-group-item list-group-item-success">Автор: {{ post.author }}</li>
  <li class="list-group-item">Название: {{ post.name }}</li>
  <li class="list-group-item">Описание: {{ post.description }}</li>
  <li class="list-group-item">Текст: {{ post }}... <a href="{% url 'posts:post_detail' post.id %}" class="text-primary" style="text-decoration: none">Читать полностью</a></li>
  <li class="list-group-item">💬 {% comment_count post.id %}| 👍 {% post_grade_like post.id %} | 👎 {% post_grade_dislike post.id%} | 👁️ {% unique_watch post.id %} | 👀 {% watch post.id %}</li>
    </ul>
        <hr>
    {% endfor %}
{% endblock %}

posts/templates/posts/post_create.html
{% extends 'base.html' %}

{% block title %}Создание поста{% endblock %}

{% block content %}
<form method="post" action="">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Создать</button>
</form>
{% endblock %}

{% block js %}
<script>
$('#id_name, #id_description, #id_text').addClass('form-control')
</script>
{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load post_tags %}

{% block title %}{{ post.name }}{% endblock %}

{% block content %}
    <h1 class="text-primary text-center">{{ post.name }}</h1>
    <hr>
        <ul class="list-group" style="box-shadow: 0 0 10px #CFE2FF">
          <li class="list-group-item active">Дата публикации: {{ post.updated_at }} 👁️ {% unique_watch post.id %} | 👀 {% watch post.id %}</li>
          <li class="list-group-item list-group-item-success">Автор: {{ post.author }}</li>
          <li class="list-group-item">Описание: {{ post.description }}</li>
          <li class="list-group-item">Текст: {{ post.text|linebreaks|urlize }}</li>
          {% if user.is_authenticated %}
              <li class="list-group-item"><a href="{% url 'posts:post_update' post.id %}" class="btn btn-warning">Изменить</a><a href="{% url 'posts:post_delete' post.id %}" class="btn btn-danger" onclick="return confirm('Вы действительно хотите удалить этот пост?')">Удалить</a></li>
          {% endif %}
        </ul>
    <br>
    <a href="{% url 'posts:grade_like' post.id %}" class="btn btn-success">👍 {% post_grade_like post.id %}</a>
    <a href="{% url 'posts:grade_dislike' post.id %}" class="btn btn-danger">👎 {% post_grade_dislike post.id %}</a>
    <br>
    <hr>
    {% for comment in objects %}
        <br>
        <ul class="list-group" style="box-shadow: 0 0 10px #CFE2FF; width: 30%">
          <li class="list-group-item active">Дата публикации: </li>
          <li class="list-group-item list-group-item-success">Автор: {{ comment.author }}</li>
          <li class="list-group-item">Текст: {{ comment.text|linebreaks|urlize }}</li>
          {% if user.is_authenticated %}
              <li class="list-group-item"><a href="{% url 'posts:comment_delete' post.id comment.id %}" class="btn btn-danger" onclick="return confirm('Вы действительно хотите удалить этот комментарий?')">Удалить</a></li>
          {% endif %}
        </ul>
    {% endfor %}
    <br>

        <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if objects.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objects.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&lt;</span>
                        </a>
                    </li>
                {% endif %}

                {% for page in objects.paginator.page_range %}
                    {% if objects.number == page %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if objects.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objects.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&gt;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objects.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
    <hr>
    <form action="" method="post">
          {% csrf_token %}
        <label for="new_author">Автор:</label><input id="new_author" name="new_author" class="form-control">
        <label for="new_comment">Комментарий:</label><textarea id="new_comment" name="new_comment" class="form-control"></textarea>
        <br>
        <button type="submit" class="btn btn-success" name="btn">Отправить</button>
    </form>
    <hr>
    <a href="{% url 'posts:posts' %}" class="btn btn-success">Все публикации</a>
{% endblock %}
{% block js %}
    <script>

    </script>
{% endblock %}

posts/templates/posts/post_list.html
{% extends 'base.html' %}
{% load post_tags %}

{% block title %}Публикации{% endblock %}

{% block content %}
    <h1 style="font-size: 36px" class="text-center text-primary">Публикации</h1>
    <hr>
    {% for post in objects %}
        <ul class="list-group" style="box-shadow: 0 0 10px #CFE2FF">
  <li class="list-group-item active">Дата публикации: {{ post.updated_at }}</li>
  <li class="list-group-item list-group-item-success">Автор: {{ post.author }}</li>
  <li class="list-group-item">Название: {{ post.name }}</li>
  <li class="list-group-item">Описание: {{ post.description }}</li>
  <li class="list-group-item">Текст: {{ post }}... <a href="{% url 'posts:post_detail' post.id %}" class="text-primary" style="text-decoration: none">Читать полностью</a></li>
  <li class="list-group-item">💬 {% comment_count post.id %}| 👍 {% post_grade_like post.id %} | 👎 {% post_grade_dislike post.id%} | 👁️ {% unique_watch post.id %} | 👀 {% watch post.id %}</li>
    </ul>
        <hr>
    {% endfor %}
    <nav aria-label="Page navigation">
            <ul class="pagination">
                {% if objects.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?page=1" aria-label="First">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objects.previous_page_number }}" aria-label="Previous">
                            <span aria-hidden="true">&lt;</span>
                        </a>
                    </li>
                {% endif %}

                {% for page in objects.paginator.page_range %}
                    {% if objects.number == page %}
                        <li class="page-item active" aria-current="page">
                            <a class="page-link" href="#">{{ page }}</a>
                        </li>
                    {% else %}
                        <li class="page-item">
                            <a class="page-link" href="?page={{ page }}">{{ page }}</a>
                        </li>
                    {% endif %}
                {% endfor %}

                {% if objects.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objects.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&gt;</span>
                        </a>
                    </li>
                    <li class="page-item">
                        <a class="page-link" href="?page={{ objects.paginator.num_pages }}" aria-label="Last">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </nav>
{% endblock %}

posts/templates/posts/post_update.html
{% extends 'base.html' %}

{% block title %}Изменинение поста{% endblock %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
    </form>
{% endblock %}

{% block js %}

{% endblock %}

templates/base.html
{% load static %}
{% load main_tags %}
{% load post_tags %}
{% main_settings as settings %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
        <title>{% block title %}{{ settings.site_name }}{% endblock %}</title>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:index' %}" data-bs-toggle="tooltip" data-bs-placement="top" title="{{ settings.site_description }}">{% if settings %}{{ settings.site_name }}{% else %}Micro Blog{% endif %}</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'posts:posts' %}">Публикации<span class="badge badge-black" style="color: lightblue">{% post_count %}</span></a>
        </li>
          {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'posts:post_create' %}" style="color: green">Создать +</a>
        </li>
          {% endif %}
        <li class="nav-item dropdown">
      </ul>
    </div>
  </div>
</nav>
<div class="container-fluid" style="margin-top: 70px">
{% if message %}
    <div class="alert alert-{{ message.type }} alert-dismissible fade show" role="alert">
  {{ message.text }}
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endif %}
{% block content %}
{% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
{% block js %}
{% endblock %}
</body>
</html>